// Public engine API.
export * from './core.js';
export * from './market.js';
export * from './fleet.js';
export * from './network.js';
export * from './maintenance.js';
export * from './staff.js';
export * from './ops.js';
export * from './finance.js';
export * from './rivals.js';
export * from './contracts.js';
export * from './events.js';
export * from './turn.js';
export * from './advisor.js';
export * from './brands.js';
export * from './regulation.js';
export * from './chronicle.js';
export * from './scenarios.js';
export * from './rivalai.js';
export * from './restructuring.js';
export * from './tutorial.js';
export * from './fit.js';
export { GLOSSARY, explain } from '../data/glossary.js';
export { aircraftById, AIRCRAFT, CLASSES, CABIN, CHECKS, CHECK_ORDER, UPGRADES, FACILITIES, MRO_PROVIDERS, mroById, CATEGORY_LABELS, CONVERSIONS, cabinUnits, seatCount, SEAT_PRODUCTS, seatProducts, defaultCabin, seatUnits, productQ, canCombi, COMBI_UNITS_PER_T, cabinGroup, FAMILIES, familyOf } from '../data/aircraft.js';
export { AIRPORTS, airportByCode, COUNTRIES, REGIONS } from '../data/airports.js';
export { RIVALS, rivalById, RIVAL_TYPES, ALLIANCES } from '../data/rivals.js';
export { ROLES, ROLE_IDS, SERVICE, SERVICE_IDS, VENTURES, RATINGS, ACTIONS, HR_POLICIES, SUPERVISOR, MANAGER } from '../data/business.js';
export * from './safety.js';
export { HISTORY, AIRSPACE, WEATHER } from '../data/history.js';
export * from '../data/eras.js';
export * from '../data/difficulty.js';
export { inProduction, inService, LIFE_LIMIT_YEARS } from '../data/aircraft.js';
