// Converts a world-atlas TopoJSON land file into src/data/land.js (lon/lat rings).
// Usage: node scripts/build-land.js path/to/land-110m.json
// Source data: Natural Earth (public domain) via the world-atlas package (ISC).
import { readFileSync, writeFileSync } from 'node:fs';

const topo = JSON.parse(readFileSync(process.argv[2], 'utf8'));
const { scale, translate } = topo.transform;
const arcs = topo.arcs.map((arc) => {
  let x = 0, y = 0;
  return arc.map(([dx, dy]) => {
    x += dx;
    y += dy;
    return [x * scale[0] + translate[0], y * scale[1] + translate[1]];
  });
});
const arcPoints = (i) => (i >= 0 ? arcs[i] : arcs[~i].slice().reverse());
const rings = [];
for (const geom of topo.objects.land.geometries) {
  const polys = geom.type === 'Polygon' ? [geom.arcs] : geom.arcs;
  for (const poly of polys) {
    for (const ring of poly) {
      const pts = ring.flatMap((i, n) => arcPoints(i).slice(n ? 1 : 0));
      if (pts.length < 4) continue;
      rings.push(pts.flatMap(([x, y]) => [Math.round(x * 10) / 10, Math.round(y * 10) / 10]));
    }
  }
}
writeFileSync(
  new URL('../src/data/land.js', import.meta.url),
  `// Generated by scripts/build-land.js from Natural Earth 1:110m land (public domain).\n// Each ring is a flat [lon, lat, lon, lat, ...] array.\nexport const LAND = ${JSON.stringify(rings)};\n`,
);
console.log(`${rings.length} rings, ${rings.reduce((s, r) => s + r.length / 2, 0)} points`);
